### PR TITLE
loopout: use max miner fee when deadline is close

### PR DESCRIPTION
**Pull request by yyforyongyu**
We can use the max miner fee to sweep when the deadline is close.

### CODE REVIEW

**Comment by alexbosworth** [comment]
If a user specifies a low max miner fee it isn't safe from a non-trust perspective

**Comment by yyforyongyu** [comment]
> If a user specifies a low max miner fee it isn't safe from a non-trust perspective

Not safe as in, when the sweep is not confirmed because the fee paid is insufficient, the `preimage` revealed in the transaction might be used by a non-trust server to collect the off-chain swap payment, then later timeout the on-chain HTLC?

**Comment by alexbosworth** [comment]
> > If a user specifies a low max miner fee it isn't safe from a non-trust perspective
> 
> Not safe as in, when the sweep is not confirmed because the fee paid is insufficient, the `preimage` revealed in the transaction might be used by a non-trust server to collect the off-chain swap payment, then later timeout the on-chain HTLC?

not safe as in, they reveal the preimage, the server collects the off-chain component of the swap, the htlc on-chain times out, the server collects the on-chain component of the swap, client loses both sides of the swap

**Comment by yyforyongyu** [comment]
Close as it's just a lame demo.

**Pull request closed without merging**
