### PR TITLE
loopd: Consider network when making LND paths

### LINKED ISSUE #430: for --network=testnet|regtest seek macaroons from default locations
Currently, loopd seeks the mainnet location for `admin.macaroon` for all networks. It should instead seek the appropriate location for each network.

Example issue

```
bash-5.1# ./loopd --network=testnet
...
loopd exited with an error: open /root/.lnd/data/chain/bitcoin/mainnet/admin.macaroon: no such file or directory
```

Inspired by https://github.com/lightninglabs/loop/issues/422

### PR DESCRIPTION
**Pull request by arshbot**
Currently, loopd doesn't take the `--network` flag or ini options when assuming the Lnd.Macaroonpath flag, which means if the user passes only `--network=regtest`, loopd will still look for the Lnd admin macaroon in the mainnet location. This PR adds a small consideration to remedy this bug. 

#### Pull Request Checklist
- [x] Update `release_notes.md` if your PR contains major features, breaking changes or bugfixes

### CODE REVIEW

**Review by carlaKC — APPROVED** [review]
LGTM 🥇

**Comment by carlaKC** [comment]
Needs a release notes entry!

**Review by yyforyongyu — APPROVED** [review]
LGTM

**Review by carlaKC — APPROVED** [review]

**Comment by carlaKC** [comment]
> @carlaKC anything left here before merge?

Nope!

**Comment by carlaKC** [comment]
@arshbot could you push again to try kick travis?

**Pull request merged**
