### PR TITLE
Prepare for lnd v0.13.0 and upcoming LiT version

### PR DESCRIPTION
**Pull request by guggero**
We want to publish a version of LiT that contains `lnd v0.13.0-beta` soon. To make sure `loopd` is _compile time_ ready for that version of `lnd` we need to bump the dependency version.

We also decided to make the `lnd` version `v0.11.1-beta` the oldest that's supported by `lndclient`, this implicitly also means we need to bump the minimum _run time_ version of `lnd` to `v0.11.1-beta`.

#### Pull Request Checklist
- [X] Update `release_notes.md` if your PR contains major features, breaking changes or bugfixes

### CODE REVIEW

**Review by alexbosworth — APPROVED** [review]

**Comment by alexbosworth** [comment]
Is this a breaking change for users on lnd 0.11.0?

**Comment by guggero** [comment]
Yes, users of `lnd v0.11.0-beta` will need to upgrade to at least `lnd v0.11.1-beta`.

**Review by carlaKC — APPROVED** [review]

**Review by bhandras — APPROVED** [review]

**Comment by guggero** [comment]
Please hold off on merging this. I think we need some fix for the "wait for lnd to be unlocked" forward compatibility for lnd `v0.13.0-beta`.

**Comment by guggero** [comment]
Updated `lndclient` to `v0.11.1-6` which fixes the "wait for lnd to be unlocked" problem. I also added a commit that fixes the double hex encoding of the pubkey in the log. Going to re-request review for a quick sanity check.

**Pull request merged**
