### PR TITLE
Add option to stop creation of macaroons

### PR DESCRIPTION
**Pull request by orbitalturtle**
When using the Lightning Terminal in stateless remote mode (described here: https://github.com/lightninglabs/lightning-terminal/issues/160), Loop shouldn't create a new macaroon. This is a small change to stop macaroons from being created when macaroon data is passed to Loop directly.

Relies on: lightninglabs/lndclient#51

### CODE REVIEW

**Comment by guggero** [comment]
See https://github.com/lightninglabs/pool/pull/272#discussion_r673108791, this also applies here.

**Review by carlaKC — COMMENTED** [review]
Also need to update this to depend on new lndclient? You can point `go.mod` to your branch while it's in review.

**Comment by guggero** [comment]
Oops, I didn't mean to close this, but apparently me removing the `lnd-14` branch did that. Can you rebase onto master and re-open the PR please?

**Comment by guggero** [comment]
I'm going to take over those PRs so they can hopefully make it into the lnd 0.14.0 release of LiT. I hope you don't mind!

**Pull request closed without merging**
